# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: tao242dn@gmail.com
author_name: Tao242dn
contract_name: auction
deployment_language: python
preset_name: production
project_name: auction-project

